### ISSUE TITLE
Data Downloading error

### ISSUE THREAD

**Issue by pdx379** [hemenkapadia/getbhavcopy#105]
plz check using win 7 MS framework 4.6 earlier was able to download data but from few days geeting error screenshot attached. plz help and solve

![get](https://user-images.githubusercontent.com/58540558/70201657-4b2e7080-173d-11ea-98fc-44908af45d1d.jpg)

**Comment by mihan81** [comment]
same problem with me using win 10

**Comment by niravshah74** [comment]
same with me...

**Comment by ghkumarchd** [comment]
same problem with me using windows10 home edition

**Comment by lakshmikanthjc** [comment]
I am not able to download EOD data since 4th Dec 2019.....do I need to make some changes?

**Comment by lakshmikanthjc** [comment]
> I am not able to download EOD data since 4th Dec 2019.....do I need to make some changes? I use Windows 7

I was able to download the data. I think this issue was due to the Thanksgiving Holiday

**Comment by bijoy2526** [comment]
same problem here,was able to  download data of 4 much later but I am trying to download data for 5th today it is not downloading can any one provide me data of 5th

**Comment by pdx379** [comment]
i found some technical or may be i dont know what should i name this. but same day after commenting error here. i tried to download again after 11am in morning and it downloaded. but on same day morning 8am from i tried but failed giving screenshot error. as abv mentioned.. again i tried next morning same error. but after 11am downloaded. one more thing i notice. i pull data from nse website to excel FO stock with 1min auto refresh. as i have screener. but from last 4days after market opening data not efreshing giving error. but after 11am it is auto refreshing without any error........ does. nse blocking or nse server issue??? plz explain.

**Comment by bijoy2526** [comment]
just tried to download it is downloading now...........don'tknow when again it will stop.

**Comment by nimishsdll** [comment]
It is downloading now.

**Comment by nimishsdll** [comment]
I think the error was rather from the NSE api and not the tool.

**Comment by lakshmikanthjc** [comment]
Not able to download data of 10th Dec .... the issue is happening quite often nowadays....pls help. thank you.

**Comment by sandeep255** [comment]
same issue for me too. Not able to download the data since Monday 10th Dec

**Comment by neilazavedo** [comment]
As has said earlier by pdx379... data is available to download after 11am .. this is a NSE related issue ..

**Comment by lakshmikanthjc** [comment]
Will check it out today at 11 am, till what time is the time slot to download....because I tried to download now at 5.44 am, but finding the same download issue.

**Comment by neilazavedo** [comment]
Just tried... I could download the data right now ...

**Comment by lakshmikanthjc** [comment]
Yes, I could download the data as well at around 6.00 pm.....thank you.

**Comment by neilazavedo** [comment]
Thanx for the update lakshmikanthjc .. now we know for sure that data is available for download after 12pm to about 6.30pm. Awesome. Happy Sunday to all ..

**Comment by hemenkapadia** [comment]
Resolved in 3.0.1a

**Comment by lakshmikanthjc** [comment]
Unfortunately, the download issue still persists.

________________________________
